version: "3"
services:
  server:
    container_name: xss_session_stealer
    build: .
    environment:
      DATABASE_HOST: postgresql
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: monsec
      DATABASE_PORT: 5432
    ports:
      - 9000:9000
      - 9001:9001
    depends_on:
      - postgresql
  postgresql:
    container_name: postgresql
    image: postgres:15.1-alpine3.16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./database:/var/lib/postgresql/data